version: '2'
services:
  biz-server:
    image: cloudvalley/biz-server
    container_name: biz-server
    network_mode: 'container:msg-server'
        expose:
      - '5800'
    ports:
      - '5800:5800'
    volumes:
      - ~/biz-server:/biz-server
      - ~/data/biz-server:/biz-server/data
      - /tmp:/tmp
    environment:
      - HOST=0.0.0.0
      - PORT=5800
    restart: always