version: '2'
services:
  cmd-server:
    image: cloudvalley/cmd-server
    container_name: cmd-server
    network_mode: 'container:msg-server'
    volumes:
      - ~/cmd-server:/cmd-server
      - ~/data/cmd-server:/cmd-server/data
      - /tmp:/tmp
    environment:
      - TURING123_API_KEY=YOUR_API_KEY
      - HOST=0.0.0.0
      - PORT=8888
      - BAIDU_FANYI_APP_ID=YOUR_APP_ID
      - BAIDU_FANYI_API_KEY=YOUR_API_KEY
      - SPEECH_RECOGNITION_SERVICE=baidu|bing
      - BAIDU_SPEECH_API_KEY=YOUR_API_KEY
      - BAIDU_SPEECH_SECRET_KEY=YOUR_SECRET_KEY
      - BING_SPEECH_API_KEY=YOUR_API_KEY
      - HEWEATHER_API_KEY=YOUR_API_KEY
    restart: always